version: "3.5"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: botronom_db
      POSTGRES_USER: root
    ports:
      - 5430:5432
    volumes:
    - type: bind
      source: ./src/database/data
      target: /var/lib/postgresql/data
  app:
    build: .
    restart: always
